name: chat_apps_kuld
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.3.0
  google_sign_in: 5.4.2
  firebase_auth: 4.1.5
  lottie: 2.0.0
  introduction_screen: 3.1.1
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.5.1
  get_storage: 2.0.3
  cloud_firestore: 4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
  uses-material-design: true

