// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWl237CN-EcFK6nNsXcX8fOfoDfEZ977w',
    appId: '1:701914833535:web:6760459d4d008849e8954a',
    messagingSenderId: '701914833535',
    projectId: 'chats-kuldii',
    authDomain: 'chats-kuldii.firebaseapp.com',
    storageBucket: 'chats-kuldii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsvgkoGLTk5ABCTJAxTN2xa6bFOdStls',
    appId: '1:701914833535:android:b33e876589fa4d2fe8954a',
    messagingSenderId: '701914833535',
    projectId: 'chats-kuldii',
    storageBucket: 'chats-kuldii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMD3w6Xtug4lXE71RMacGWV0dpTqdojY',
    appId: '1:701914833535:ios:fea844ccc93d4cfee8954a',
    messagingSenderId: '701914833535',
    projectId: 'chats-kuldii',
    storageBucket: 'chats-kuldii.appspot.com',
    androidClientId: '701914833535-1h7v6os135oehuht5rgvt6tqo69hq6dv.apps.googleusercontent.com',
    iosClientId: '701914833535-rc0mrq938b1v4u763p9cmbue9klovvvg.apps.googleusercontent.com',
    iosBundleId: 'com.chatappkuld.chatAppsKuld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjMD3w6Xtug4lXE71RMacGWV0dpTqdojY',
    appId: '1:701914833535:ios:fea844ccc93d4cfee8954a',
    messagingSenderId: '701914833535',
    projectId: 'chats-kuldii',
    storageBucket: 'chats-kuldii.appspot.com',
    androidClientId: '701914833535-1h7v6os135oehuht5rgvt6tqo69hq6dv.apps.googleusercontent.com',
    iosClientId: '701914833535-rc0mrq938b1v4u763p9cmbue9klovvvg.apps.googleusercontent.com',
    iosBundleId: 'com.chatappkuld.chatAppsKuld',
  );
}
